# Generated by Django 4.0.6 on 2022-07-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account')),
                ('start_time', models.DateTimeField(verbose_name='Start_time')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department')),
            ],
        ),
    ]
