# Generated by Django 4.0.6 on 2022-07-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='start_time',
            field=models.DateField(verbose_name='Start_time'),
        ),
    ]
