# Generated by Django 4.0.6 on 2022-07-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_specialnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialnum',
            name='mobile',
            field=models.CharField(max_length=32, verbose_name='Mobile'),
        ),
    ]
