# Generated by Django 4.0.6 on 2022-07-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_specialnum_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialnum',
            name='Price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
